print("\n===== Selamat datang di program penghitung volume =====\n")
phi = float(3.14)

print("\n===== Menghitung Volume Kubus =====\n")
print("Volume Kubus : sisi x sisi x sisi")
sisiKubus = float(input("Masukkan panjang sisi : "))
volumeKubus = float(sisiKubus * sisiKubus * sisiKubus)
print("Volume Kubus :", volumeKubus)

print("\n===== Menghitung Volume Balok ===== \n")
print("Volume Balok : panjang x lebar x tinggi")
panjangBalok = float(input("Masukkan panjang balok : "))
lebarBalok = float(input("Masukkan lebar balok : "))
tinggiBalok = float(input("Masukkan tinggi balok : "))
volumeBalok = float(panjangBalok * lebarBalok * tinggiBalok)
print("Volume Balok :", volumeBalok)

print("\n===== Menghitung Volume Tabung ===== \n")
print("Volume Tabung : phi x jari-jari x jari-jari x tinggi")
jariTabung = float(input("Masukkan jari-jari tabung : "))
tinggiTabung = float(input("Masukkan tinggi tabung : "))
volumeTabung = float(phi * jariTabung * jariTabung * tinggiTabung)
print("Volume Tabung :", volumeTabung)

print("\n===== Menghitung Volume Prisma ===== \n")
print("Volume Prisma : luas alas x tinggi")
alasPrisma = float(input("Masukkan luas alas prisma : "))
tinggiPrisma = float(input("Masukkan tinggi prisma : "))
volumePrisma = float(alasPrisma * tinggiPrisma)
print("Volume Prisma :", volumePrisma)

print("\n===== Menghitung Volume Limas ===== \n")
print("Volume Limas : 1/3 x luas alas x tinggi")
alasLimas = float(input("Masukkan luas alas limas : "))
tinggiLimas = float(input("Masukkan tinggi limas : "))
volumeLimas = float(alasLimas * tinggiLimas / 3)
print("Volume Limas :", volumeLimas)

print("\n===== Menghitung Volume Kerucut ===== \n")
print("Volume Kerucut : 1/3 x phi x jari-jari x jari-jari x tinggi")
jariKerucut = float(input("Masukkan jari-jari kerucut : "))
tinggiKerucut = float(input("Masukkan tinggi kerucut : "))
volumeKerucut = float(phi * jariKerucut * jariKerucut * tinggiKerucut / 3)
print("Volume Kerucut :", volumeKerucut)

print("\n===== Menghitung Volume Bola ===== \n")
print("Volume Bola : 4/3 x phi x jari-jari x jari-jari x jari-jari")
jariBola = float(input("Masukkan jari-jari bola : "))
volumeBola = float(4 / 3 * phi * jariBola * jariBola * jariBola)
print("Volume Bola :", volumeBola)